### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by wagnerand** [kewisch/amo-helper#2]
I randomly opened the error console and saw:

"resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://amoqueue/webextension/content/browseraction/dashboard.js"
line 12: TypeError

Stack
"parseQueueNumbers@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://amoqueue/webextension/content/browseraction/dashboard.js:12:22@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://amoqueue/webextension/content/browseraction/dashboard.js:29:71"

**Comment by kewisch** [comment]
A lot has changed since this error, I'm not able to reproduce so let's close. Let me know if this happens again.
